package logger

const (
	// Level Debug...
	LevelDebug = "debug"
	// Level Info...
	LevelInfo = "info"
	// Level Warn...
	LevelWarn = "warn"
	// Level Error...
	LevelError = "error"
	// Level Panic...
	LevelPanic = "panic"
	// LevelFatal...
	LevelFatal = "fatal"
)
